pecsapp:
  file-storage:
    directory: /tmp/pecsapp/images

logging:
  level:
    net.pkhsolutions.pecsapp: DEBUG

spring:
  datasource:
    url: jdbc:h2:file:/tmp/pecsapp/db
  jpa:
    hibernate:
      ddl-auto: update
